include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 110

analyzer:
  language:
    strict-casts: true
  errors:
    unawaited_futures: warning
  exclude:
    - build/**
    - android/**
    - ios/**

linter:
  rules:
    - unawaited_futures
    - avoid_print
    - prefer_const_constructors
    - require_trailing_commas: false
