"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-02 08:55:16.774053
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_definition",
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=60), nullable=False),
        sa.Column("summary", sa.String(length=240), nullable=False),
        sa.Column("min_age", sa.Integer(), nullable=False),
        sa.Column("max_age", sa.Integer(), nullable=False),
        sa.Column(
            "options_schema",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("assessment_note", sa.String(length=240), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "parent",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("idp_subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=True),
        sa.Column("marketing_opt_in", sa.Boolean(), nullable=False),
        sa.Column("store_transcripts", sa.Boolean(), nullable=False),
        sa.Column("product_analytics", sa.Boolean(), nullable=False),
        sa.Column("data_choices_confirmed", sa.Boolean(), nullable=False),
        sa.Column(
            "onboarding_step",
            sa.Enum(
                "verify_email",
                "intro",
                "connect_toy",
                "child_profile",
                "preferences",
                "done",
                name="onboarding_step",
            ),
            nullable=False,
        ),
        sa.Column("notify_session_summaries", sa.Boolean(), nullable=False),
        sa.Column("notify_device_offline", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deletion_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idp_subject"),
    )
    op.create_table(
        "child",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=40), nullable=False),
        sa.Column("birth_year", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["parent.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_child_parent_id"), "child", ["parent_id"], unique=False)
    op.create_table(
        "device",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("serial", sa.String(length=64), nullable=False),
        sa.Column("setup_code_hash", sa.String(length=128), nullable=False),
        sa.Column("hardware_rev", sa.String(length=32), nullable=False),
        sa.Column("firmware_version", sa.String(length=32), nullable=True),
        sa.Column("latest_firmware_version", sa.String(length=32), nullable=True),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("wifi_ssid", sa.String(length=64), nullable=True),
        sa.Column("desired_config_version", sa.Integer(), nullable=False),
        sa.Column("applied_config_version", sa.Integer(), nullable=False),
        sa.Column("active_child_id", sa.Uuid(), nullable=True),
        sa.Column("is_simulated", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["active_child_id"], ["child.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("serial"),
    )
    op.create_table(
        "learning_preferences",
        sa.Column("child_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["child_id"], ["child.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("child_id"),
    )
    op.create_table(
        "claim_attempt",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=True),
        sa.Column("parent_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "completed", "expired", "cancelled", "failed", name="claim_status"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["device.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["parent.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_claim_attempt_device_id"), "claim_attempt", ["device_id"], unique=False
    )
    op.create_index(
        op.f("ix_claim_attempt_parent_id"), "claim_attempt", ["parent_id"], unique=False
    )
    op.create_table(
        "device_command",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "apply_config",
                "play_greeting",
                "enter_wifi_setup",
                "factory_reset",
                "check_firmware",
                name="command_kind",
            ),
            nullable=False,
        ),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "delivered", "acknowledged", "failed", "expired", name="command_status"
            ),
            nullable=False,
        ),
        sa.Column("config_version", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.String(length=120), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["device.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["parent.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_device_command_device_id"), "device_command", ["device_id"], unique=False
    )
    op.create_table(
        "device_config_version",
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["device.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("device_id", "version"),
    )
    op.create_table(
        "device_credential",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("secret_hash", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["device.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_device_credential_device_id"), "device_credential", ["device_id"], unique=False
    )
    op.create_table(
        "device_ownership",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["device.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["parent.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_device_ownership_parent_id"), "device_ownership", ["parent_id"], unique=False
    )
    op.create_index(
        "uq_device_ownership_active",
        "device_ownership",
        ["device_id"],
        unique=True,
        postgresql_where=sa.text("released_at IS NULL"),
        sqlite_where=sa.text("released_at IS NULL"),
    )
    op.create_table(
        "latency_sample",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("metric", sa.String(length=48), nullable=False),
        sa.Column("value_ms", sa.Float(), nullable=False),
        sa.Column("conditions", sa.String(length=120), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["device.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_latency_sample_device_id"), "latency_sample", ["device_id"], unique=False
    )
    op.create_index(op.f("ix_latency_sample_metric"), "latency_sample", ["metric"], unique=False)
    op.create_table(
        "learning_session",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=True),
        sa.Column("child_id", sa.Uuid(), nullable=False),
        sa.Column("activity_key", sa.String(length=40), nullable=False),
        sa.Column("client_session_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "state",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["activity_key"],
            ["activity_definition.key"],
        ),
        sa.ForeignKeyConstraint(["child_id"], ["child.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["device_id"], ["device.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "client_session_id"),
    )
    op.create_index(
        op.f("ix_learning_session_child_id"), "learning_session", ["child_id"], unique=False
    )
    op.create_index(
        op.f("ix_learning_session_device_id"), "learning_session", ["device_id"], unique=False
    )
    op.create_table(
        "assessment_result",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("item_index", sa.Integer(), nullable=False),
        sa.Column("item_prompt", sa.String(length=240), nullable=False),
        sa.Column("expected", sa.String(length=120), nullable=True),
        sa.Column("response_text", sa.String(length=240), nullable=True),
        sa.Column(
            "outcome",
            sa.Enum("correct", "needs_practice", "uncertain", name="assessment_outcome"),
            nullable=False,
        ),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("source_version", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["learning_session.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assessment_result_session_id"), "assessment_result", ["session_id"], unique=False
    )
    op.create_table(
        "conversation_turn",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("speaker", sa.String(length=10), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["learning_session.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversation_turn_session_id"), "conversation_turn", ["session_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_conversation_turn_session_id"), table_name="conversation_turn")
    op.drop_table("conversation_turn")
    op.drop_index(op.f("ix_assessment_result_session_id"), table_name="assessment_result")
    op.drop_table("assessment_result")
    op.drop_index(op.f("ix_learning_session_device_id"), table_name="learning_session")
    op.drop_index(op.f("ix_learning_session_child_id"), table_name="learning_session")
    op.drop_table("learning_session")
    op.drop_index(op.f("ix_latency_sample_metric"), table_name="latency_sample")
    op.drop_index(op.f("ix_latency_sample_device_id"), table_name="latency_sample")
    op.drop_table("latency_sample")
    op.drop_index(
        "uq_device_ownership_active",
        table_name="device_ownership",
        postgresql_where=sa.text("released_at IS NULL"),
        sqlite_where=sa.text("released_at IS NULL"),
    )
    op.drop_index(op.f("ix_device_ownership_parent_id"), table_name="device_ownership")
    op.drop_table("device_ownership")
    op.drop_index(op.f("ix_device_credential_device_id"), table_name="device_credential")
    op.drop_table("device_credential")
    op.drop_table("device_config_version")
    op.drop_index(op.f("ix_device_command_device_id"), table_name="device_command")
    op.drop_table("device_command")
    op.drop_index(op.f("ix_claim_attempt_parent_id"), table_name="claim_attempt")
    op.drop_index(op.f("ix_claim_attempt_device_id"), table_name="claim_attempt")
    op.drop_table("claim_attempt")
    op.drop_table("learning_preferences")
    op.drop_table("device")
    op.drop_index(op.f("ix_child_parent_id"), table_name="child")
    op.drop_table("child")
    op.drop_table("parent")
    op.drop_table("activity_definition")
    for enum_name in (
        "onboarding_step",
        "claim_status",
        "command_kind",
        "command_status",
        "assessment_outcome",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
